package catalogo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 23 17:37:58 CST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ToksCaCatTasasImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdTasa {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getIdTasa();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setIdTasa((Number)value);
            }
        }
        ,
        Tasa {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getTasa();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setTasa((Number)value);
            }
        }
        ,
        FechaInicio {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getFechaInicio();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setFechaInicio((Date)value);
            }
        }
        ,
        FechaFin {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getFechaFin();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setFechaFin((Date)value);
            }
        }
        ,
        Estatus {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getEstatus();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setEstatus((String)value);
            }
        }
        ,
        Periodo {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getPeriodo();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setPeriodo((String)value);
            }
        }
        ,
        CreadoPor {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getCreadoPor();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setCreadoPor((Number)value);
            }
        }
        ,
        FechaCreacion {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getFechaCreacion();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setFechaCreacion((Date)value);
            }
        }
        ,
        ActualizadoPor {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getActualizadoPor();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setActualizadoPor((Number)value);
            }
        }
        ,
        FechaActualizacion {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getFechaActualizacion();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setFechaActualizacion((Date)value);
            }
        }
        ,
        Xchar1 {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getXchar1();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setXchar1((String)value);
            }
        }
        ,
        Xchar2 {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getXchar2();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setXchar2((String)value);
            }
        }
        ,
        Xchar3 {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getXchar3();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setXchar3((String)value);
            }
        }
        ,
        Xchar4 {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getXchar4();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setXchar4((String)value);
            }
        }
        ,
        Xchar5 {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getXchar5();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setXchar5((String)value);
            }
        }
        ,
        Xnumber1 {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getXnumber1();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setXnumber1((Number)value);
            }
        }
        ,
        Xnumber2 {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getXnumber2();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setXnumber2((Number)value);
            }
        }
        ,
        Xnumber3 {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getXnumber3();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setXnumber3((Number)value);
            }
        }
        ,
        Xnumber4 {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getXnumber4();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setXnumber4((Number)value);
            }
        }
        ,
        Xnumber5 {
            public Object get(ToksCaCatTasasImpl obj) {
                return obj.getXnumber5();
            }

            public void put(ToksCaCatTasasImpl obj, Object value) {
                obj.setXnumber5((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ToksCaCatTasasImpl object);

        public abstract void put(ToksCaCatTasasImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDTASA = AttributesEnum.IdTasa.index();
    public static final int TASA = AttributesEnum.Tasa.index();
    public static final int FECHAINICIO = AttributesEnum.FechaInicio.index();
    public static final int FECHAFIN = AttributesEnum.FechaFin.index();
    public static final int ESTATUS = AttributesEnum.Estatus.index();
    public static final int PERIODO = AttributesEnum.Periodo.index();
    public static final int CREADOPOR = AttributesEnum.CreadoPor.index();
    public static final int FECHACREACION = AttributesEnum.FechaCreacion.index();
    public static final int ACTUALIZADOPOR = AttributesEnum.ActualizadoPor.index();
    public static final int FECHAACTUALIZACION = AttributesEnum.FechaActualizacion.index();
    public static final int XCHAR1 = AttributesEnum.Xchar1.index();
    public static final int XCHAR2 = AttributesEnum.Xchar2.index();
    public static final int XCHAR3 = AttributesEnum.Xchar3.index();
    public static final int XCHAR4 = AttributesEnum.Xchar4.index();
    public static final int XCHAR5 = AttributesEnum.Xchar5.index();
    public static final int XNUMBER1 = AttributesEnum.Xnumber1.index();
    public static final int XNUMBER2 = AttributesEnum.Xnumber2.index();
    public static final int XNUMBER3 = AttributesEnum.Xnumber3.index();
    public static final int XNUMBER4 = AttributesEnum.Xnumber4.index();
    public static final int XNUMBER5 = AttributesEnum.Xnumber5.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ToksCaCatTasasImpl() {
    }

    /**
     * Gets the attribute value for IdTasa, using the alias name IdTasa.
     * @return the IdTasa
     */
    public Number getIdTasa() {
        return (Number)getAttributeInternal(IDTASA);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdTasa.
     * @param value value to set the IdTasa
     */
    public void setIdTasa(Number value) {
        setAttributeInternal(IDTASA, value);
    }

    /**
     * Gets the attribute value for Tasa, using the alias name Tasa.
     * @return the Tasa
     */
    public Number getTasa() {
        return (Number)getAttributeInternal(TASA);
    }

    /**
     * Sets <code>value</code> as the attribute value for Tasa.
     * @param value value to set the Tasa
     */
    public void setTasa(Number value) {
        setAttributeInternal(TASA, value);
    }

    /**
     * Gets the attribute value for FechaInicio, using the alias name FechaInicio.
     * @return the FechaInicio
     */
    public Date getFechaInicio() {
        return (Date)getAttributeInternal(FECHAINICIO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FechaInicio.
     * @param value value to set the FechaInicio
     */
    public void setFechaInicio(Date value) {
        setAttributeInternal(FECHAINICIO, value);
    }

    /**
     * Gets the attribute value for FechaFin, using the alias name FechaFin.
     * @return the FechaFin
     */
    public Date getFechaFin() {
        return (Date)getAttributeInternal(FECHAFIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for FechaFin.
     * @param value value to set the FechaFin
     */
    public void setFechaFin(Date value) {
        setAttributeInternal(FECHAFIN, value);
    }

    /**
     * Gets the attribute value for Estatus, using the alias name Estatus.
     * @return the Estatus
     */
    public String getEstatus() {
        return (String)getAttributeInternal(ESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Estatus.
     * @param value value to set the Estatus
     */
    public void setEstatus(String value) {
        setAttributeInternal(ESTATUS, value);
    }

    /**
     * Gets the attribute value for Periodo, using the alias name Periodo.
     * @return the Periodo
     */
    public String getPeriodo() {
        return (String)getAttributeInternal(PERIODO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Periodo.
     * @param value value to set the Periodo
     */
    public void setPeriodo(String value) {
        setAttributeInternal(PERIODO, value);
    }

    /**
     * Gets the attribute value for CreadoPor, using the alias name CreadoPor.
     * @return the CreadoPor
     */
    public Number getCreadoPor() {
        return (Number)getAttributeInternal(CREADOPOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreadoPor.
     * @param value value to set the CreadoPor
     */
    public void setCreadoPor(Number value) {
        setAttributeInternal(CREADOPOR, value);
    }

    /**
     * Gets the attribute value for FechaCreacion, using the alias name FechaCreacion.
     * @return the FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date)getAttributeInternal(FECHACREACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for FechaCreacion.
     * @param value value to set the FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }

    /**
     * Gets the attribute value for ActualizadoPor, using the alias name ActualizadoPor.
     * @return the ActualizadoPor
     */
    public Number getActualizadoPor() {
        return (Number)getAttributeInternal(ACTUALIZADOPOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualizadoPor.
     * @param value value to set the ActualizadoPor
     */
    public void setActualizadoPor(Number value) {
        setAttributeInternal(ACTUALIZADOPOR, value);
    }

    /**
     * Gets the attribute value for FechaActualizacion, using the alias name FechaActualizacion.
     * @return the FechaActualizacion
     */
    public Date getFechaActualizacion() {
        return (Date)getAttributeInternal(FECHAACTUALIZACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for FechaActualizacion.
     * @param value value to set the FechaActualizacion
     */
    public void setFechaActualizacion(Date value) {
        setAttributeInternal(FECHAACTUALIZACION, value);
    }

    /**
     * Gets the attribute value for Xchar1, using the alias name Xchar1.
     * @return the Xchar1
     */
    public String getXchar1() {
        return (String)getAttributeInternal(XCHAR1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xchar1.
     * @param value value to set the Xchar1
     */
    public void setXchar1(String value) {
        setAttributeInternal(XCHAR1, value);
    }

    /**
     * Gets the attribute value for Xchar2, using the alias name Xchar2.
     * @return the Xchar2
     */
    public String getXchar2() {
        return (String)getAttributeInternal(XCHAR2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xchar2.
     * @param value value to set the Xchar2
     */
    public void setXchar2(String value) {
        setAttributeInternal(XCHAR2, value);
    }

    /**
     * Gets the attribute value for Xchar3, using the alias name Xchar3.
     * @return the Xchar3
     */
    public String getXchar3() {
        return (String)getAttributeInternal(XCHAR3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xchar3.
     * @param value value to set the Xchar3
     */
    public void setXchar3(String value) {
        setAttributeInternal(XCHAR3, value);
    }

    /**
     * Gets the attribute value for Xchar4, using the alias name Xchar4.
     * @return the Xchar4
     */
    public String getXchar4() {
        return (String)getAttributeInternal(XCHAR4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xchar4.
     * @param value value to set the Xchar4
     */
    public void setXchar4(String value) {
        setAttributeInternal(XCHAR4, value);
    }

    /**
     * Gets the attribute value for Xchar5, using the alias name Xchar5.
     * @return the Xchar5
     */
    public String getXchar5() {
        return (String)getAttributeInternal(XCHAR5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xchar5.
     * @param value value to set the Xchar5
     */
    public void setXchar5(String value) {
        setAttributeInternal(XCHAR5, value);
    }

    /**
     * Gets the attribute value for Xnumber1, using the alias name Xnumber1.
     * @return the Xnumber1
     */
    public Number getXnumber1() {
        return (Number)getAttributeInternal(XNUMBER1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xnumber1.
     * @param value value to set the Xnumber1
     */
    public void setXnumber1(Number value) {
        setAttributeInternal(XNUMBER1, value);
    }

    /**
     * Gets the attribute value for Xnumber2, using the alias name Xnumber2.
     * @return the Xnumber2
     */
    public Number getXnumber2() {
        return (Number)getAttributeInternal(XNUMBER2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xnumber2.
     * @param value value to set the Xnumber2
     */
    public void setXnumber2(Number value) {
        setAttributeInternal(XNUMBER2, value);
    }

    /**
     * Gets the attribute value for Xnumber3, using the alias name Xnumber3.
     * @return the Xnumber3
     */
    public Number getXnumber3() {
        return (Number)getAttributeInternal(XNUMBER3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xnumber3.
     * @param value value to set the Xnumber3
     */
    public void setXnumber3(Number value) {
        setAttributeInternal(XNUMBER3, value);
    }

    /**
     * Gets the attribute value for Xnumber4, using the alias name Xnumber4.
     * @return the Xnumber4
     */
    public Number getXnumber4() {
        return (Number)getAttributeInternal(XNUMBER4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xnumber4.
     * @param value value to set the Xnumber4
     */
    public void setXnumber4(Number value) {
        setAttributeInternal(XNUMBER4, value);
    }

    /**
     * Gets the attribute value for Xnumber5, using the alias name Xnumber5.
     * @return the Xnumber5
     */
    public Number getXnumber5() {
        return (Number)getAttributeInternal(XNUMBER5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xnumber5.
     * @param value value to set the Xnumber5
     */
    public void setXnumber5(Number value) {
        setAttributeInternal(XNUMBER5, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param idTasa key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number idTasa) {
        return new Key(new Object[]{idTasa});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("catalogo.ToksCaCatTasas");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        java.sql.Timestamp datetime = new java.sql.Timestamp(System.currentTimeMillis());
        super.create(attributeList);
        /* setFechaCreacion(new Date(datetime));
        setFechaInicio(new Date(datetime));
        setEstatus("A");
        setPeriodo("A"); */
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }
}
